site_name: routelit-flask
repo_url: https://github.com/routelit/routelit-flask
site_url: https://routelit.github.io/routelit-flask
site_description: A Flask adapter for the RouteLit framework, enabling seamless integration of RouteLit's reactive UI components with Flask web applications.
site_author: Rolando Gómez Tabar
edit_uri: edit/main/docs/
repo_name: routelit/routelit-flask
copyright: Maintained by <a href="https://routelit.com">routelit</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/routelit_flask"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/routelit/routelit-flask
    - icon: fontawesome/brands/python
      link: https://pypi.org/routelit/routelit-flask

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
